# Generated by Django 2.2.7 on 2021-12-06 20:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=200)),
                ('apellidos_alumno', models.CharField(max_length=200)),
                ('dni_alumno', models.CharField(max_length=20)),
                ('correo_alumno', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo_Formativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciclo_formativo', models.CharField(max_length=200)),
                ('siglas_ciclo_formativo', models.CharField(choices=[('ASIR', 'ASIR'), ('DAM', 'DAM'), ('DAW', 'DAW'), ('SMR', 'SMR'), ('SMRV', 'SMRV'), ('ASIR_ERASMUS', 'ASIR_ERASMUS'), ('DAM_ERASMUS', 'DAM_ERASMUS'), ('DAW_ERASMUS', 'DAW_ERASMUS'), ('SMR_ERASMUS', 'SMR_ERASMUS'), ('FPB_IO_1', 'FPB_IO_1'), ('FPB_IO_2', 'FPB_IO_2')], default='ASIR', max_length=20)),
                ('clave_ciclo_formativo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_academico', models.CharField(max_length=50)),
                ('inicio_realizacion_fct', models.DateField(verbose_name='Inicio de FCT')),
                ('fin_realizacion_fct', models.DateField(verbose_name='Fin de FCT')),
                ('horas_totales_fct', models.CharField(default='400', max_length=10)),
                ('ciclo_formativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fct.Ciclo_Formativo')),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_convenio', models.CharField(max_length=200)),
                ('fecha_convenio', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha firma convenio')),
                ('nombre_representante', models.CharField(max_length=200)),
                ('apellidos_representante', models.CharField(max_length=200)),
                ('nombre_tutor_empresa', models.CharField(max_length=200)),
                ('apellidos_tutor_empresa', models.CharField(max_length=200)),
                ('dni_representante', models.CharField(max_length=20)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('localidad_empresa', models.CharField(max_length=200)),
                ('provincia_empresa', models.CharField(max_length=200)),
                ('calle_empresa', models.CharField(max_length=250)),
                ('cod_postal_empresa', models.CharField(max_length=200)),
                ('cif_empresa', models.CharField(max_length=50)),
                ('telefono_empresa', models.CharField(max_length=50)),
                ('fax_empresa', models.CharField(max_length=50)),
                ('correo_empresa', models.CharField(max_length=200)),
                ('horario_empresa', models.CharField(default='No hay información disponible', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Instituto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_director', models.CharField(max_length=200)),
                ('apellidos_director', models.CharField(max_length=200)),
                ('dni_director', models.CharField(max_length=20)),
                ('nombre_instituto', models.CharField(max_length=100)),
                ('codigo_instituto', models.CharField(max_length=20)),
                ('localidad_instituto', models.CharField(max_length=20)),
                ('provincia_instituto', models.CharField(max_length=20)),
                ('calle_instituto', models.CharField(max_length=200)),
                ('cod_postal_instituto', models.CharField(max_length=10)),
                ('cif_instituto', models.CharField(max_length=20)),
                ('telefono_instituto', models.CharField(max_length=15)),
                ('fax_instituto', models.CharField(max_length=15)),
                ('correo_instituto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor_Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tutor_centro', models.CharField(max_length=200)),
                ('apellidos_tutor_centro', models.CharField(max_length=200)),
                ('correo_tutor_centro', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Alumno_Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fct.Alumno')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fct.Curso')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fct.Datos_Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='tutor_centro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fct.Tutor_Centro'),
        ),
    ]
